#!/bin/sh

# Install qttools5-dev-tools

BRAND='solydxk'
LANGS='en ca da de es fr hr it ja lt nb nl pl pt_BR pt ru sr tr'

cd ./calamares/branding/$BRAND
mkdir -p lang
rm lang/*.qm
for L in $(echo $LANGS); do
    # Create ts files
    lupdate show.qml -no-obsolete -source-language en -ts ../../../ts/calamares-${BRAND}_${L}.ts -target-language ${L}
    # En is the base translation file (as pot file for po translations)
    if [ "${L}" != 'en' ]; then
        # Create qm files
        lrelease ../../../ts/calamares-${BRAND}_${L}.ts -nounfinished -qm "./lang/calamares-${BRAND}_${L}.qm"
    fi
done
# Delete empty qm files
find ./lang -type f -name "*.qm" -size -2k -delete
