<?xml version="1.0" ?><!DOCTYPE TS><TS language="hr" sourcelanguage="en_US" version="2.1">
<context>
    <name>show</name>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="48"/>
        <source>&lt;h3&gt;Thank you for choosing SolydXK&lt;/h3&gt;&lt;br /&gt;You&apos;ve chosen a Linux distribution that is:&lt;br /&gt;&lt;ul&gt;&lt;li&gt;Secure and stable&lt;/li&gt;&lt;li&gt;Fast and responsive&lt;/li&gt;&lt;li&gt;Desktop-ready&lt;/li&gt;&lt;/ul&gt;&lt;br /&gt;Enjoy this new release and thank you for choosing SolydXK.&lt;br /&gt;The installation takes 15-30 minutes, depending on your settings.</source>
        <translation>&lt;h3&gt;Hvala što ste odabrali SolydXK&lt;/h3&gt;&lt;br /&gt;Odabrali ste Linux distribuciju koja je:&lt;br /&gt;&lt;ul&gt;&lt;li&gt;Sigurna i stabilna&lt;/li&gt;&lt;li&gt;Brza i responzivna&lt;/li&gt;&lt;li&gt;Spremna za desktop&lt;/li&gt;&lt;/ul&gt;&lt;br /&gt;Uživajte u ovom novom izdanju i hvala na odabiru SolydXK.&lt;br /&gt;Instalacija će trajati 15-30 minuta, ovisno o vašim postavkama.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="69"/>
        <source>&lt;h3&gt;Standing on the shoulders of Giants&lt;/h3&gt;&lt;br /&gt;SolydXK is a Debian-based GNU/Linux distribution derived from and compatible with Debian.&lt;br /&gt;&lt;br /&gt;SolydXK uses either the lightweight Xfce desktop for SolydX or the highly configurable and stunningly appealing KDE desktop for SolydK.&lt;br /&gt;&lt;br /&gt;Our innovations, the rapid development of Debian and the huge Debian package selection make SolydXK one of the most attractive desktop operating systems available to home users.</source>
        <translation>&lt;h3&gt;Stoji na ramenima Divova&lt;/h3&gt;&lt;br /&gt;SolydXK je Debian-bazirana GNU/Linux distribucija izvedena iz i kompatibilna s Debianom.&lt;br /&gt;&lt;br /&gt;SolydXK koristi lagani Xfce desktop za SolydX, ili visoko prilagodljivi i nevjerojatno privlačan KDE desktop za SolydK.&lt;br /&gt;&lt;br /&gt;Naše inovacije, brzi razvoj Debiana i ogroman izbor Debian paketa čine SolydXK jednim od najatraktivnijih desktop operativnih sustava za kućne korisnike.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="89"/>
        <source>&lt;h3&gt;Out of the box&lt;/h3&gt;&lt;br /&gt;Firefox, Thunderbird, and LibreOffice come pre-installed in SolydXK, so you can get started immediately with the desktop and the Internet.&lt;br /&gt;&lt;br /&gt;Unlike other Linux distributions SolydXK is also ready to play your music, internet videos and more.&lt;br /&gt;&lt;br /&gt;A wide variety of software can be installed with a click of the mouse.&lt;br /&gt;&lt;br /&gt;SolydXK is compatible with most popular file formats such as: docx, xlsx, doc, xls, pdf, zip, rar, mp3, mpg, and many more.</source>
        <translation>&lt;h3&gt;Iz kutije&lt;/h3&gt;&lt;br /&gt;Firefox, Thunderbird i LibreOffice dolaze kao dio paketa SolydXK, tako da možete odmah početi s radom na radnoj površini i internetu.&lt;br /&gt;&lt;br /&gt;Za razliku od drugih Linux distribucija SolydXK je spreman za reprodukciju glazbe, video sadržaja i još mnogo toga.&lt;br /&gt;&lt;br /&gt;Širok izbor softvera može se instalirati klikom miša.&lt;br /&gt;&lt;br /&gt;SolydXK je kompatibilan s većinom popularnih formata datoteka, kao što su: docx, xlsx, doc, xls, pdf, zip, rar, mp3, mpg, i još mnogo toga.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="110"/>
        <source>&lt;h3&gt;Office tools are ready to use as soon as you install SolydXK&lt;/h3&gt;&lt;br /&gt;LibreOffice, a powerful office software suite, comes built into SolydXK.&lt;br /&gt;&lt;br /&gt;LibreOffice is very easy to learn and use.&lt;br /&gt;&lt;br /&gt;You can use it to create letters, presentations and spreadsheets, as well as diagrams and databases.&lt;br /&gt;&lt;br /&gt;LibreOffice uses the standard OpenDocument format and it works with documents from other popular office applications including WordPerfect and Microsoft Office.</source>
        <translation>&lt;h3&gt;Office alati su spremni za korištenje čim instalirate SolydXK&lt;/h3&gt;&lt;br /&gt;LibreOffice, snažan uredski softver paket, dolazi ugrađen u SolydXK.&lt;br /&gt;&lt;br /&gt;LibreOffice je vrlo jednostavan za naučiti i koristiti.&lt;br /&gt;&lt;br /&gt;Možete ga koristiti za stvaranje pisma, prezentacija i proračunskih tablica, kao i dijagrama i baza podataka.&lt;br /&gt;&lt;br /&gt;LibreOffice koristi standardni OpenDocument format i to radi s dokumentima iz drugih popularnih uredskih aplikacija, uključujući WordPerfect i Microsoft Office.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="131"/>
        <source>&lt;h3&gt;An alternative to mainstream operating systems&lt;/h3&gt;&lt;br /&gt;SolydXK is easy to use, powerful and configurable.&lt;br /&gt;&lt;br /&gt;SolydXK is safe and stable. Unlike other operating systems, it is not prone to computer viruses or spyware, it does not suffer from disk fragmentation, and it has no registry that requires periodic cleaning.&lt;br /&gt;&lt;br /&gt;SolydXK can detect other operating systems and install itself beside them.You can choose which operating system to launch when you start the computer.</source>
        <translation>&lt;h3&gt;Alternativa glavnim operativnim sustavima&lt;/h3&gt;&lt;br /&gt;SolydXK je lagan za upotrebu, moćan i vrlo podesiv.&lt;br /&gt;&lt;br /&gt;SolydXK je siguran i stabilan. Za razliku od drugih operativnih sustava, nije sklon računalnim virusima ili spyware-u, te ne pati od fragmentacije diska i nema registar koji zahtijeva periodično čišćenje.&lt;br /&gt;&lt;br /&gt;SolydXK može otkriti druge operativne sustave i instalirati se pored njih. Možete odabrati koji operativni sustav želite pokrenuti prilikom pokretanja računala.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="151"/>
        <source>&lt;h3&gt;Safe updates&lt;/h3&gt;&lt;br /&gt;Some operating systems make updating your system harder than it really needs to be. SolydXK thinks upgrades should be quick and easy, and then get out of the way.&lt;br /&gt;&lt;br /&gt;The Update Manager sits discreetly in your system tray and lets you know when updates are available. You don&apos;t have to apply updates when you don&apos;t want to. The Update Manager won&apos;t pop up or annoy you in any way.&lt;br /&gt;&lt;br /&gt;All updated files are maintained and closely checked by trusted developers and maintainers.&lt;br /&gt;&lt;br /&gt;All files are stored in special secure repositories for your use.&lt;br /&gt;&lt;br /&gt;The security repository is synchronized daily.</source>
        <translation>&lt;h3&gt;Sigurnosne nadogradnje&lt;/h3&gt;&lt;br /&gt;Neki operativni sustavi čine ažuriranje sustava teže nego što stvarno treba biti. SolydXK misli da bi nadogradnja trebala biti brza i jednostavna, a zatim se maknuti s puta.&lt;br /&gt;&lt;br /&gt;Upravitelj nadogradnji sjedi diskretno u traci sustava i obavještava vas kada su dostupna ažuriranja. Ne morate primijeniti nadogranje kada ne želite. Update Manager neće se pojaviti ili uznemiravati vas na bilo koji način.&lt;br /&gt;&lt;br /&gt;Sve ažurirane datoteke održavaju i pažljivo provjeravaju pouzdani programeri i održavatelji.&lt;br /&gt;&lt;br /&gt;Sve datoteke su pohranjene u posebnim sigurnim repositorijima spremnim za korištenje.&lt;br /&gt;&lt;br /&gt;Sigurnosni repozitorij se sinkronizira dnevno.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="173"/>
        <source>&lt;h3&gt;A great community&lt;/h3&gt;&lt;br /&gt;The SolydXK community is one of the best on the Internet. Our users provide most of our funding, as well as ideas, artwork and sometimes even source code.&lt;br /&gt;&lt;br /&gt;SolydXK users are happy to share their passion and enthusiasm and are eager to help. Don&apos;t hesitate to ask questions on the forums or to get involved in the community.&lt;br /&gt;&lt;br /&gt;Send us your feedback and tell us about your experience. We&apos;ll listen to your ideas and use them to further improve SolydXK.</source>
        <translation>&lt;h3&gt;Sjajna zajednica&lt;/h3&gt;&lt;br /&gt;SolydXK zajednica je jedna od najboljih na Internetu. Naši korisnici osiguravaju većinu naših sredstava, doprinose idejama, ilustracijama, a ponekad čak i izvorni kod.&lt;br /&gt;&lt;br /&gt;SolydXK korisnici su sretni podijeliti svoju strast i entuzijazam, te žele pomoći. Ne oklijevajte postavljati pitanja na forumima ili se uključiti u zajednicu.&lt;br /&gt;&lt;br /&gt;Šaljite nam povratne informacije i prenesite nam svoja iskustva. Mi čujemo vaše ideje i koristimo ih u daljnjem usavršavanju SolydXK.</translation>
    </message>
</context>
</TS>