<?xml version="1.0" ?><!DOCTYPE TS><TS language="pl" sourcelanguage="en_US" version="2.1">
<context>
    <name>show</name>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="48"/>
        <source>&lt;h3&gt;Thank you for choosing SolydXK&lt;/h3&gt;&lt;br /&gt;You&apos;ve chosen a Linux distribution that is:&lt;br /&gt;&lt;ul&gt;&lt;li&gt;Secure and stable&lt;/li&gt;&lt;li&gt;Fast and responsive&lt;/li&gt;&lt;li&gt;Desktop-ready&lt;/li&gt;&lt;/ul&gt;&lt;br /&gt;Enjoy this new release and thank you for choosing SolydXK.&lt;br /&gt;&lt;br /&gt;The installation takes 15-30 minutes, depending on your settings.</source>
        <translation>&lt;h3&gt;Dziękujemy za wybranie SolydXK&lt;/h3&gt;&lt;br /&gt;Wybrałaś/eś dystrybucję Linuxa, która jest:&lt;br /&gt;&lt;ul&gt;&lt;li&gt;bezpieczna i stabilna&lt;/li&gt;&lt;li&gt;szybka i godna zaufania&lt;/li&gt;&lt;li&gt;gotowa do pracy&lt;/li&gt;&lt;/ul&gt;&lt;br /&gt;Wierzymy, że znajdziesz satysfakcję pracując z nowym wydaniem SolydXK i dziękujemy Ci za wybranie naszej dystrybucji.&lt;br /&gt;&lt;br /&gt;Instalacja trwa  15-30 min w zależności od Twojego sprzętu.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="69"/>
        <source>&lt;h3&gt;Standing on the shoulders of Giants&lt;/h3&gt;&lt;br /&gt;SolydXK is a Debian-based GNU/Linux distribution derived from and compatible with Debian.&lt;br /&gt;&lt;br /&gt;SolydXK uses either the lightweight Xfce desktop for SolydX or the highly configurable and stunningly appealing KDE desktop for SolydK.&lt;br /&gt;&lt;br /&gt;Our innovations, the rapid development of Debian and the huge Debian package selection make SolydXK one of the most attractive desktop operating systems available to home users.</source>
        <translation>&lt;h3&gt;Stojąc na ramionach Gigantów&lt;/h3&gt;&lt;br /&gt;SolydXK jest dystrybucją GNU/Linux  opartą na Debianie i w pełni z nim kompatybilną.&lt;br /&gt;&lt;br /&gt;SolydXK używa lekkiego środowiska graficznego Xfce w wersji SolydX oraz niezwykle bogatego i konfigurowalnego środowiska KDE w wersji SolydK.&lt;br /&gt;&lt;br /&gt;Imponujący rozwój Debiana, przeogromny zbiór pakietów w repozytoriach Debiana oraz nasze innowacje czynią SolydXK jednym z najbardziej atrakcyjnych systemów operacyjnych dla użytkowników domowych.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="89"/>
        <source>&lt;h3&gt;Out of the box&lt;/h3&gt;&lt;br /&gt;Firefox, Thunderbird, and LibreOffice come pre-installed in SolydXK, so you can get started immediately with the desktop and the Internet.&lt;br /&gt;&lt;br /&gt;Unlike other Linux distributions SolydXK is also ready to play your music, internet videos and more.&lt;br /&gt;&lt;br /&gt;A wide variety of software can be installed with a click of the mouse.&lt;br /&gt;&lt;br /&gt;SolydXK is compatible with most popular file formats such as: docx, xlsx, doc, xls, pdf, zip, rar, mp3, mpg, and many more.</source>
        <translation>&lt;h3&gt;System jest od razu gotowy do akcji&lt;/h3&gt;&lt;br /&gt;Firefox, Thunderbird i LibreOffice są preinstalowane w SolydXK, co umożliwia natychmiastowy dostęp do materiałów w sieci internet, obsługę poczty i pracę biurową.&lt;br /&gt;&lt;br /&gt;SolydXK jest po instalacji od razu gotów do odtwarzania muzyki i plików video.&lt;br /&gt;&lt;br /&gt;System umożliwia instalację rozmaitego oprogramowania za pomocą kliknięcia myszki.&lt;br /&gt;&lt;br /&gt;SolydXK jest kompatybilny z większością popularnych formatów plików, takich jak: docx, xlsx, doc, xls, pdf, zip, rar, mp3, mpg, i wiele innych.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="110"/>
        <source>&lt;h3&gt;Office tools are ready to use as soon as you install SolydXK&lt;/h3&gt;&lt;br /&gt;LibreOffice, a powerful office software suite, comes built into SolydXK.&lt;br /&gt;&lt;br /&gt;LibreOffice is very easy to learn and use.&lt;br /&gt;&lt;br /&gt;You can use it to create letters, presentations and spreadsheets, as well as diagrams and databases.&lt;br /&gt;&lt;br /&gt;LibreOffice uses the standard OpenDocument format and it works with documents from other popular office applications including WordPerfect and Microsoft Office.</source>
        <translation>&lt;h3&gt;Narzędzia biurowe są gotowe do użytku zaraz po instalacji systemu&lt;/h3&gt;&lt;br /&gt;LibreOffice, potężny &quot;kombajn&quot; biurowy jest wbudowany w SolydXK.&lt;br /&gt;&lt;br /&gt;LibreOfficejego użycie jest proste i intuicyjne.&lt;br /&gt;&lt;br /&gt;Możesz używać LibreOffice do pisania listów, tworzenia prezentacji, arkuszy kalkulacyjnych, wykresów i baz danych.&lt;br /&gt;&lt;br /&gt;LibreOfficeużywa standardowego formatu OpenDocument a może pracować z dokumentami z innych popularnych aplikacji takich jak WordPerfect i Microsoft Office.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="131"/>
        <source>&lt;h3&gt;An alternative to mainstream operating systems&lt;/h3&gt;&lt;br /&gt;SolydXK is easy to use, powerful and configurable.&lt;br /&gt;&lt;br /&gt;SolydXK is safe and stable. Unlike other operating systems, it is not prone to computer viruses or spyware, it does not suffer from disk fragmentation, and it has no registry that requires periodic cleaning.&lt;br /&gt;&lt;br /&gt;SolydXK can detect other operating systems and install itself beside them.You can choose which operating system to launch when you start the computer.</source>
        <translation>&lt;h3&gt;Alternatywa dla głównych systemów operacyjnych&lt;/h3&gt;&lt;br /&gt;SolydXK jest wysoce konfigurowalny, łatwy w obsłudze i drzemią w nim potężne moce.&lt;br /&gt;&lt;br /&gt;SolydXK jest bezpieczny i stabilny. Nie jest podatny na ataki, nie obawia się wirusów, malware i spyware. Nie wie, co to fragmentacja dysku i nie wymaga czyszczenia rejestru.&lt;br /&gt;&lt;br /&gt;SolydXK wykrywa podczas instalacji inne systemy operacyjne i instaluje się obok nich, nie ingerując w ich ustawienia. Możesz wybrać który system operacyjny zechcesz uruchomić podczas startu komputera.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="151"/>
        <source>&lt;h3&gt;Safe updates&lt;/h3&gt;&lt;br /&gt;Some operating systems make updating your system harder than it really needs to be. SolydXK thinks upgrades should be quick and easy, and then get out of the way.&lt;br /&gt;&lt;br /&gt;The Update Manager sits discreetly in your system tray and lets you know when updates are available. You don&apos;t have to apply updates when you don&apos;t want to. The Update Manager won&apos;t pop up or annoy you in any way.&lt;br /&gt;&lt;br /&gt;All updated files are maintained and closely checked by trusted developers and maintainers.&lt;br /&gt;&lt;br /&gt;All files are stored in special secure repositories for your use.&lt;br /&gt;&lt;br /&gt;The security repository is synchronized daily.</source>
        <translation>&lt;h3&gt;Aktualizacje bezpieczeństwa&lt;/h3&gt;&lt;br /&gt;Zgodnie z filozofią SolydXK aktualizacje są szybkie i łatwe a po ich zakończeniu można o nich zapomnieć. Nie ma tu skomplikowanych procesów aktualizacji.&lt;br /&gt;&lt;br /&gt;Menedżer Aktualizacji spoczywa spokojnie w tacce systemowej i powiadamia Cię, kiedy są dostępne aktualizacje. Nie obliguje Cię to do ich instalacji, zrobisz to w dogodnym momencie. Menedżer nie będzie wysyłał żadnych irytujących monitów.&lt;br /&gt;&lt;br /&gt;Wszystkie pliki aktualizacyjne są pod troskliwą opieką zaufanych programistów.&lt;br /&gt;&lt;br /&gt;Pliki do Twego uzytku są przechowywane w zabezpieczonych repozytoriach.&lt;br /&gt;&lt;br /&gt;Repozytorium bezpieczeństwa jest synchronizowane codziennie.</translation>
    </message>
    <message>
        <location filename="../calamares/branding/solydxk/show.qml" line="173"/>
        <source>&lt;h3&gt;A great community&lt;/h3&gt;&lt;br /&gt;The SolydXK community is one of the best on the Internet. Our users provide most of our funding, as well as ideas, artwork and sometimes even source code.&lt;br /&gt;&lt;br /&gt;SolydXK users are happy to share their passion and enthusiasm and are eager to help. Don&apos;t hesitate to ask questions on the forums or to get involved in the community.&lt;br /&gt;&lt;br /&gt;Send us your feedback and tell us about your experience. We&apos;ll listen to your ideas and use them to further improve SolydXK.</source>
        <translation>&lt;h3&gt;Wspaniała społeczność&lt;/h3&gt;&lt;br /&gt;Społeczność SolydXK jest jedną z najlepszych w Internecie. Nasi użytkownicy dostarczają nam idee, prace graficzne, niekiedy kod źródłowy oraz zaopatruja nas w znaczną część funduszy.&lt;br /&gt;&lt;br /&gt;Nasi użytkownicy to pasjonaci chętnie dzielący się swoją wiedzą i zawsze gotowi do pomocy. Nie wahaj się zadawać pytań na naszym forum. Włącz się w naszą społeczność.&lt;br /&gt;&lt;br /&gt;Napisz do nas i podziel się swoimi doświadczeniami. Wykorzystamy Twoje idee w dalszym udoskonalaniu SolydXK.</translation>
    </message>
</context>
</TS>