#!/bin/sh
set -e

case "$1" in
    install|upgrade)
	# Hide upstream calamares icon when this package is installed
        dpkg-divert --quiet --package calamares-settings-solydxk \
                    --divert /usr/share/applications/calamares.desktop.orig \
		    --rename /usr/share/applications/calamares.desktop
    
    # Remove unneeded fstrim job
    if [ -e "/etc/cron.weekly/fstrim_job" ]; then
        rm "/etc/cron.weekly/fstrim_job"
    fi
    ;;
esac

#DEBHELPER#
